
#pragma namespace ("\\\\.\\root\\cimv2\\SMS")
#pragma deleteclass("ext_system_secureboot_servicing", NOFAIL)
[SMS_Report(TRUE),SMS_Group_Name("ext_system_secureboot_servicing"),SMS_Class_ID("ext_system_secureboot_servicing")]
Class ext_system_secureboot_servicing: SMS_Class_Template
{
[SMS_Report(TRUE),key] string KeyName;
[SMS_Report(TRUE)] Uint32 WindowsUEFICA2023Capable;
[SMS_Report(TRUE)] String UEFICA2023Status;
[SMS_Report(TRUE)] String BucketHash;
[SMS_Report(TRUE)] String ConfidenceLevel;
};
