//========================
// Added extensions start
//========================

#pragma namespace ("\\\\.\\root\\cimv2")
#pragma deleteclass("ext_system_secureboot", NOFAIL)
[DYNPROPS]
Class ext_system_secureboot
{
[key] string KeyName;
Uint32 AvailableUpdates;
};

[DYNPROPS]
Instance of ext_system_secureboot
{
KeyName="RegKeyToMOF";
[PropertyContext("Local|HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\SecureBoot|AvailableUpdates"),Dynamic,Provider("RegPropProv")] AvailableUpdates;
};

#pragma namespace ("\\\\.\\root\\cimv2")
#pragma deleteclass("ext_system_secureboot_servicing", NOFAIL)
[DYNPROPS]
Class ext_system_secureboot_servicing
{
[key] string KeyName;
Uint32 WindowsUEFICA2023Capable;
String UEFICA2023Status;
String BucketHash;
String ConfidenceLevel;
};

[DYNPROPS]
Instance of ext_system_secureboot_servicing
{
KeyName="RegKeyToMOF";
[PropertyContext("Local|HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\SecureBoot\\Servicing|WindowsUEFICA2023Capable"),Dynamic,Provider("RegPropProv")] WindowsUEFICA2023Capable;
[PropertyContext("Local|HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\SecureBoot\\Servicing|UEFICA2023Status"),Dynamic,Provider("RegPropProv")] UEFICA2023Status;
[PropertyContext("Local|HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\SecureBoot\\Servicing|BucketHash"),Dynamic,Provider("RegPropProv")] BucketHash;
[PropertyContext("Local|HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\SecureBoot\\Servicing|ConfidenceLevel"),Dynamic,Provider("RegPropProv")] ConfidenceLevel;
};

//========================
// Added extensions end
//========================
